name: DevSecOps CI with Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t devsecops-rgr-app .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.25.0
        with:
          image-ref: 'devsecops-rgr-app'
          format: 'table'
          exit-code: '0'